### ISSUE TITLE
/

### ISSUE THREAD

**Issue by kenvix** [XcodeGhostSource/XcodeGhost#38]
# 敢问你X国政府何时承认过墙的存在？
ps: 我下载需要加速工具

**Comment by jobin-sun** [comment]
不要那么激进, Apple被墙了吗?

**Comment by Alien-2001** [comment]
赞同，没有墙自然会去官网下，在国内下都是被速度逼的

**Comment by balthild** [comment]
技术之界，既无恶意，万事皆允。

**Comment by Vrchz** [comment]
楼主你很有智慧

**Comment by dukai** [comment]
因为别人作恶，自己也要作恶？！这是什么逻辑？技术试验没问题，但是偷窥别人的隐私，无论从什么角度，无论是道德还是法律，都需要受到谴责和惩罚！

**Comment by balthild** [comment]
@dukai 偷窥隐私这句话说的真6，源码都有了，你倒是说说有哪些隐私被偷窥？机型？还是系统版本？如果你觉得这是隐私，那还用什么smart phone ? 我看是 stupid phone 吧？

**Comment by liuxuan30** [comment]
@kenvix 我TM就不明白了，违法的事情，谈政治干什么？张口闭口你国政府？你爹妈知道你这么跪舔他国是感到很自豪是么？你觉得你在他国就会有尊严么？你觉得美国没种族歧视么？

再说，我就是从官网下的Xcode，联通宽带，速度至少也有500KB-1M以上,我就不明白了，3,4G的东西，这跟GFW有什么关系？墙你下Xcode了？

**Comment by zenghaojim33** [comment]
Xcode里放木马都能跟墙联系上了，下一步是不是该继续怪体制的问题啊？

**Comment by Martin404** [comment]
关墙什么关系？我读书少

**Comment by kenvix** [comment]
@liuxuan30 请问我哪句话提到美狗了

**Comment by nareix** [comment]
这事情是一系列中国特色杯具的集合：GFW，偷懒的程序猿，钻了空子的作者，不想买真苹果的公司。

不光是墙的问题。

**Comment by liuxuan30** [comment]
@kenvix 那你国是哪个国？

**Comment by CyclonicDyna** [comment]
当时看到因为下载速度慢而转去下载非官方的XCODE有点震惊。我在国外用校园网下载xcode 一般10MB/s, 几分钟就下载完了。我猜国内肯定是有些速度限制的

**Comment by liuxuan30** [comment]
@lilin3336298 我的联通宽带稳定在1MB/s以上，下一个Xcode也就一小时，有时候速度更快。所以喷速度慢的我觉得就很扯，好像是GFW给你限速了所以成了你用百度网盘的理由一样，蹩脚的理由

**Comment by jobin-sun** [comment]
确实和GFW一点关系没有，只能说冤枉坏人了，不过这木马的作者也不是好人

**Comment by zmcadam** [comment]
我今天用校园网试了下，确实是从早上下到吃晚饭，只能说有些地方的网络的确渣，但墙不墙的有关系么～

**Comment by eric3zhao** [comment]
这和墙有关系？这不是因为国际带宽的住口太小导致的吗，海底光缆都几年没升级了

**Comment by marsprince** [comment]
局域网闭环已经形成了，当所有的开发者已经习惯于百度而不是谷歌，这种事情发生只是早晚

**Comment by huangzonghao** [comment]
商业化的软件居然都不用 official distribution 来 build。。。无论恶意代码作者动机如何软件开发者们也都脱不了干系

**Comment by alex-chan** [comment]
其实，我发现akamai的有些域名被GFW了，苹果用来做cdn的
