### ISSUE TITLE
希望作者能给出能检测XCode是否被感染的简单方式，显得诚意一点。

### ISSUE THREAD

**Issue by molon** [XcodeGhostSource/XcodeGhost#6]
如题。

**Comment by majestyhao** [comment]
看sha1

**Comment by androidcn** [comment]
@majestyhao 正解

**Comment by molon** [comment]
@majestyhao 可是我已经安装好了啊。sha1方法只能查dmg文件吧。
我查到法子了，说是感染的话，`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/`下会有`Library/Frameworks/CoreServices.framework`，否则没有。
还好在下的是OK的。:)
